# Generated by Django 6.0.6 on 2026-06-27 20:22

import cloudinary.models
import django.db.models.deletion
import markdownx.models
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('resume_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('tagline', models.CharField(max_length=255)),
                ('bio', markdownx.models.MarkdownxField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.profile')),
            ],
            options={
                'verbose_name': 'profile Translation',
                'db_table': 'core_profile_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='core_profile_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
