# Generated by Django 6.0.6 on 2026-06-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GITHUB', 'GitHub'), ('LINKEDIN', 'LinkedIn'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
