# Generated by Django 6.0.6 on 2026-06-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtranslation',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experiencetranslation',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
