# Generated by Django 6.0.6 on 2026-06-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_educationtranslation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationtranslation',
            name='field_of_study',
            field=models.CharField(default='sh', max_length=200),
            preserve_default=False,
        ),
    ]
